### ISSUE TITLE
SIGSEGV on linux/386

### ISSUE THREAD

**Issue by watermint** [watermint/bwlimit#1]
SIGSEGV happens on linux/386 environment like below.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8049e0c]

goroutine 29 [running]:
sync/atomic.AddUint64(0x18b7a7e4, 0x1, 0x0, 0x8, 0x0)
	/usr/local/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/watermint/toolbox/vendor/github.com/watermint/bwlimit.(*Bwlimit).issue(0x18b7a7d0, 0x0, 0x0)
	/go/src/github.com/watermint/toolbox/vendor/github.com/watermint/bwlimit/bwlimit.go:96 +0xa0
github.com/watermint/toolbox/vendor/github.com/watermint/bwlimit.(*Bwlimit).Reader(0x18b7a7d0, 0x855e610, 0x18b5cec8, 0x0)
	/go/src/github.com/watermint/toolbox/vendor/github.com/watermint/bwlimit/bwlimit.go:114 +0x25
```

**Comment by watermint** [comment]
The issue related to memory alignment of uint64.
See discussion at https://github.com/golang/go/issues/6404
